### PR TITLE
add freebsd support

### PR DESCRIPTION
**Pull request by hoanga**
the following changeset allows go-llvm (as well as tinygo) to compile on freebsd (tested on freebsd 14.3). without the changes applied the following error occurs when trying to compile on freebsd

```
$ uname -a
FreeBSD quincy 14.3-RELEASE FreeBSD 14.3-RELEASE releng/14.3-n271432-8c9ce319fef7 GENERIC amd64

$ go build ./...
# tinygo.org/x/go-llvm
./bitwriter.go:16:10: fatal error: 'llvm-c/BitWriter.h' file not found
   16 | #include "llvm-c/BitWriter.h"
      |          ^~~~~
```

### CODE REVIEW

**Comment by b0ch3nski** [comment]
I've seen other projects using https://github.com/vmactions/freebsd-vm

**Comment by hoanga** [comment]
> While I'm not opposed to this, I'm somewhat worried about having to maintain this - and likely breaking it. Is there a way to test these things in CI, even if it's just to see whether it compiles? (I guess that might be possible by installing a FreeBSD sysroot from somewhere?)

these are good points. i've setup an example ci workflow under a separate [branch](https://github.com/hoanga/go-llvm/tree/freebsd-support-ci) that tests using vm in freebsd approach (sample job run [here](https://github.com/hoanga/go-llvm/actions/runs/17767798558/job/50495493993)). if that is acceptable as is, some options to go forward with are either:

* update pull request with updated branch
* fold changes into current branch with PR

i am not sure if adding a vm action might become unwieldy in everday use on this project (i imagine for some other much faster iterating projects, the extra build time might become a possible issue) but looks like it works. the current approach favors pushing all the logic into 1 vm as i am not sure if trying to spawn a matrix of jobs for vms is a great idea for github actions. i understand some other ci flavors like cirrus ci do offer freebsd support as well if that is an option that might be considered (at the cost of extra workflow definitions)

**Comment by hoanga** [comment]
> I have refactored the config files here: #71 With this change, FreeBSD support would just mean a few extra lines in these config files and they'd be easy to keep up to date. It's been like this in TinyGo and hasn't been an issue so far. See: https://github.com/tinygo-org/tinygo/blob/release/cgo/libclang_config_llvm20.go
> 
> @hoanga do you think that's a good idea? In that case, I can merge #71 and this PR could be remade on top of that. I can't guarantee FreeBSD will continue to work, but it's harder to accidentally mess up than if FreeBSD support still exists in separate files.

the refactoring looks a little cleaner from what i can tell. i am used to and have seen the per-os file pattern separation in go in other projects. however, if tinygo is using an alternate strategy that is working for the project, having less overall multiple conventions to decrease maintenance burden makes sense to me. the changes look okay to me and i can rebase the changes that would make sense afterwards. 

my ulterior goal is to get the tinygo port updated in freebsd-ports so having less patches to add onto the ports system would be preferred.

**Comment by hoanga** [comment]
i updated the [freebsd-support-ci](https://github.com/hoanga/go-llvm/tree/freebsd-support-ci) branch to incorporate changes from #71. 

sample job results are [here](https://github.com/hoanga/go-llvm/actions/runs/17803177140/job/50608150381). looks okay for llvm19 and llvm20. llvm21 package does look available in package repos referenced in vm.

**Comment by hoanga** [comment]
> I think you could utilize the 'matrix' feature like it's done for other OS for a cleaner CI setup
> 
> ```
> strategy:
>   matrix:
>     llvm: [19, 20]
> ```

i am skeptical that enabling vm actions within a matrix is a good idea (see [earlier comment](https://github.com/tinygo-org/go-llvm/pull/69#issuecomment-3298870916)) even if it 'cleans up' the yaml declarations.

also see [this](https://github.com/hoanga/go-llvm/actions/runs/17813281138)

**Comment by hoanga** [comment]
> > also see [this](https://github.com/hoanga/go-llvm/actions/runs/17813281138)
> 
> @hoanga I think that this pipeline has failed because of the mistake in yaml here:
> 

yes, you are correct. i made another attempt attempting the matrix with better results ([here](https://github.com/hoanga/go-llvm/actions/runs/17830534521)). the _freebsd-support-ci_ should have the latest changes.

much appreciated on the gentle pointer to fixing an (obvious) pebkac entry error.

**Comment by hoanga** [comment]
> (just making it clear this PR needs some updates to be ready to merge, see comment above)

i've rebased the changes for freebsd on current master. i originally also tried to put in the ci definitions for freebsd but i have removed the freebsd ci for now as it seems that the ci runs can be [fickle](https://github.com/tinygo-org/go-llvm/actions/runs/17993995247) with added vm actions. 

i can add it back in if the finicky behavior is acceptable or i can create a separate PR if that is preferred.

File: llvm_config_llvm19.go [hunk 1]
```diff
@@ -8,6 +8,9 @@ package llvm
 // #cgo darwin,arm64 CPPFLAGS: -I/opt/homebrew/opt/llvm@19/include   -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS
 // #cgo darwin,arm64 CXXFLAGS: -std=c++17
 // #cgo darwin,arm64 LDFLAGS: -L/opt/homebrew/opt/llvm@19/lib -Wl,-search_paths_first -Wl,-headerpad_max_install_names -lLLVM -lz -lm
+// #cgo freebsd CPPFLAGS: -I/usr/local/llvm19/include -I/usr/local/llvm19/include/llvm-c -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS
+// #cgo freebsd CXXFLAGS: -std=c++17
+// #cgo freebsd LDFLAGS: -L/usr/local/llvm19/lib -lLLVM
 // #cgo linux        CPPFLAGS: -I/usr/include/llvm-19 -I/usr/include/llvm-c-19 -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS
```
Comment (aykevl) [inline llvm_config_llvm19.go:14]: Can you indent the lines like this, consistent with the rest of the file?

```suggestion
// #cgo freebsd      CPPFLAGS: -I/usr/local/llvm19/include -I/usr/local/llvm19/include/llvm-c -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS
// #cgo freebsd      CXXFLAGS: -std=c++17
// #cgo freebsd      LDFLAGS: -L/usr/local/llvm19/lib -lLLVM
// #cgo linux        CPPFLAGS: -I/usr/include/llvm-19 -I/usr/include/llvm-c-19 -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS
```

(Same goes for the other two files).

**Comment by aykevl** [comment]
Thank you! This will get pulled the next time we update go-llvm in TinyGo.
You can make a PR if you want to have this updated sooner.
